# Generated by Django 5.2.9 on 2025-12-06 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_data', '0004_add_validation_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description_short', models.CharField(blank=True, max_length=200)),
                ('description_long', models.TextField(blank=True)),
                ('default_parameters', models.JSONField(blank=True, default=dict, help_text="Default strategy parameters (e.g., {'stop_loss': 0.02, 'take_profit': 0.05})")),
                ('analytic_tools_used', models.JSONField(blank=True, default=list, help_text="List of analytical tool names used by this strategy (e.g., ['SMA', 'RSI'])")),
                ('example_code', models.TextField(blank=True, help_text='Optional example code or pseudocode for the strategy')),
                ('globally_enabled', models.BooleanField(default=False, help_text='If True, strategy is globally enabled (can be activated per symbol)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Strategy Definition',
                'verbose_name_plural': 'Strategy Definitions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StrategyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Per-symbol parameter overrides (merges with strategy default_parameters)')),
                ('enabled', models.BooleanField(default=False, help_text='If True, strategy is active for this symbol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.ForeignKey(blank=True, help_text='If None, this assignment applies to all symbols globally', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strategy_assignments', to='market_data.symbol')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='strategies.strategydefinition')),
            ],
            options={
                'verbose_name': 'Strategy Assignment',
                'verbose_name_plural': 'Strategy Assignments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['symbol', 'enabled'], name='strategies__symbol__67eb27_idx'), models.Index(fields=['strategy'], name='strategies__strateg_73ed22_idx'), models.Index(condition=models.Q(('symbol__isnull', True)), fields=['enabled'], name='strategies_global_idx')],
                'constraints': [models.UniqueConstraint(fields=('symbol', 'strategy'), name='unique_symbol_strategy'), models.UniqueConstraint(condition=models.Q(('symbol__isnull', True)), fields=('strategy',), name='unique_global_strategy')],
            },
        ),
    ]
