# Generated by Django 5.2.9 on 2025-12-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategydefinition',
            name='required_tool_configs',
            field=models.JSONField(blank=True, default=list, help_text="Required tool configurations with parameters and mappings. Format: [{'tool_name': 'SMA', 'parameters': {'period': 20}, 'parameter_mapping': {'period': 'fast_period'}, 'display_name': 'Fast SMA', 'locked': True}]"),
        ),
    ]
