# Generated by Django 5.2.9 on 2025-12-02 15:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('base_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('ticker', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(1)])),
                ('type', models.CharField(choices=[('stock', 'Stock'), ('crypto', 'Cryptocurrency'), ('etf', 'ETF'), ('forex', 'Forex')], default='stock', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=10)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='symbols', to='market_data.exchange')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='symbols', to='market_data.provider')),
            ],
            options={
                'ordering': ['ticker'],
            },
        ),
        migrations.CreateModel(
            name='OHLCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('timeframe', models.CharField(choices=[('daily', 'Daily'), ('hourly', 'Hourly'), ('minute', 'Minute')], default='daily', max_length=10)),
                ('open', models.DecimalField(decimal_places=8, max_digits=20)),
                ('high', models.DecimalField(decimal_places=8, max_digits=20)),
                ('low', models.DecimalField(decimal_places=8, max_digits=20)),
                ('close', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volume', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ohlcv_data', to='market_data.symbol')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='symbol',
            index=models.Index(fields=['ticker'], name='market_data_ticker_503d2d_idx'),
        ),
        migrations.AddIndex(
            model_name='symbol',
            index=models.Index(fields=['exchange'], name='market_data_exchang_a3d734_idx'),
        ),
        migrations.AddIndex(
            model_name='symbol',
            index=models.Index(fields=['provider'], name='market_data_provide_04f625_idx'),
        ),
        migrations.AddIndex(
            model_name='symbol',
            index=models.Index(fields=['status'], name='market_data_status_e4b645_idx'),
        ),
        migrations.AddIndex(
            model_name='ohlcv',
            index=models.Index(fields=['symbol', 'timestamp', 'timeframe'], name='market_data_symbol__f95a20_idx'),
        ),
        migrations.AddIndex(
            model_name='ohlcv',
            index=models.Index(fields=['symbol', 'timeframe', '-timestamp'], name='market_data_symbol__58970e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ohlcv',
            unique_together={('symbol', 'timestamp', 'timeframe')},
        ),
    ]
