# Generated by Django 5.2.9 on 2025-12-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0002_alter_symbol_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='disabled', max_length=10),
        ),
    ]
