# Generated by Django 5.2.9 on 2025-12-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0003_alter_symbol_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='validation_reason',
            field=models.TextField(blank=True, help_text='Reason why data validation failed (if invalid)'),
        ),
        migrations.AddField(
            model_name='symbol',
            name='validation_status',
            field=models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid'), ('pending', 'Pending Validation')], default='pending', help_text='Data validation status', max_length=20),
        ),
    ]
