# Generated by Django 5.2.9 on 2025-12-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0004_add_validation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='access_key_id',
            field=models.CharField(blank=True, help_text='S3 Access Key ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='bucket_name',
            field=models.CharField(blank=True, help_text='S3 bucket name for flat files', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='endpoint_url',
            field=models.URLField(blank=True, help_text='S3 endpoint URL (e.g., https://files.massive.com)', null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='secret_access_key',
            field=models.CharField(blank=True, help_text='S3 Secret Access Key', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='api_key',
            field=models.CharField(blank=True, help_text='API key or access key', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='base_url',
            field=models.URLField(blank=True, help_text='Base URL for API or S3 endpoint', null=True),
        ),
    ]
