# Generated by Django 5.2.9 on 2026-04-25 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0005_add_provider_s3_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_utc', models.TimeField(help_text='Market open time expressed in UTC')),
                ('close_utc', models.TimeField(help_text='Market close time expressed in UTC')),
                ('weekdays', models.CharField(default='1,2,3,4,5', help_text='Comma-separated list of ISO weekdays this schedule applies to (1=Mon … 7=Sun). Default 1,2,3,4,5 = Mon–Fri.', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='market_data.exchange')),
            ],
            options={
                'verbose_name': 'Exchange Schedule',
                'verbose_name_plural': 'Exchange Schedules',
                'ordering': ['exchange__code', 'open_utc'],
                'indexes': [models.Index(fields=['active', 'open_utc'], name='market_data_active_2a5020_idx'), models.Index(fields=['exchange', 'active'], name='market_data_exchang_41fe68_idx')],
                'unique_together': {('exchange', 'open_utc', 'close_utc', 'weekdays')},
            },
        ),
    ]
