# Generated by Django 5.2.9 on 2025-12-04 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_data', '0003_alter_symbol_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('default_parameters', models.JSONField(blank=True, default=dict)),
                ('category', models.CharField(choices=[('indicator', 'Technical Indicator'), ('statistical', 'Statistical Tool'), ('transformation', 'Data Transformation')], default='indicator', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tool Definition',
                'verbose_name_plural': 'Tool Definitions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ToolAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('style', models.JSONField(blank=True, default=dict, help_text='Styling options: color, line_width, line_style, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_assignments', to='market_data.symbol')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='analytical_tools.tooldefinition')),
            ],
            options={
                'verbose_name': 'Tool Assignment',
                'verbose_name_plural': 'Tool Assignments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IndicatorValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('value', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional indicator-specific data (e.g., MACD signal, histogram)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='analytical_tools.toolassignment')),
            ],
            options={
                'verbose_name': 'Indicator Value',
                'verbose_name_plural': 'Indicator Values',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['assignment', 'timestamp'], name='analytical__assignm_179564_idx'), models.Index(fields=['assignment', '-timestamp'], name='analytical__assignm_91db7a_idx')],
                'unique_together': {('assignment', 'timestamp')},
            },
        ),
        migrations.AddIndex(
            model_name='toolassignment',
            index=models.Index(fields=['symbol', 'enabled'], name='analytical__symbol__5137f2_idx'),
        ),
        migrations.AddIndex(
            model_name='toolassignment',
            index=models.Index(fields=['tool'], name='analytical__tool_id_855c56_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='toolassignment',
            unique_together={('symbol', 'tool')},
        ),
    ]
