# Generated by Django 5.2.9 on 2025-12-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolassignment',
            name='subchart',
            field=models.BooleanField(default=False, help_text='If True, indicator will be displayed in a subchart below the main chart'),
        ),
    ]
