# Generated by Django 5.2.9 on 2025-12-05 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_tools', '0002_toolassignment_subchart'),
        ('market_data', '0003_alter_symbol_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolassignment',
            name='symbol',
            field=models.ForeignKey(blank=True, help_text='If None, this assignment applies to all symbols globally', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tool_assignments', to='market_data.symbol'),
        ),
        migrations.AddIndex(
            model_name='toolassignment',
            index=models.Index(condition=models.Q(('symbol__isnull', True)), fields=['enabled'], name='analyt_global_idx'),
        ),
    ]
