# Generated by Django 5.2.9 on 2025-12-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_tools', '0003_make_tool_assignment_symbol_nullable'),
        ('market_data', '0003_alter_symbol_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='toolassignment',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='toolassignment',
            constraint=models.UniqueConstraint(fields=('symbol', 'tool'), name='unique_symbol_tool'),
        ),
        migrations.AddConstraint(
            model_name='toolassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('symbol__isnull', True)), fields=('tool',), name='unique_global_tool'),
        ),
    ]
