# Generated by Django 5.2.9 on 2025-12-06 11:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backtest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Optional name for this backtest', max_length=200)),
                ('start_date', models.DateTimeField(help_text='Backtest start date')),
                ('end_date', models.DateTimeField(help_text='Backtest end date')),
                ('split_ratio', models.FloatField(default=0.7, help_text='Training/test split ratio (e.g., 0.7 = 70% training, 30% testing)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('strategy_parameters', models.JSONField(blank=True, default=dict, help_text='Strategy parameters used for this backtest')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if backtest failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Backtest',
                'verbose_name_plural': 'Backtests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BacktestStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_trades', models.IntegerField(default=0)),
                ('winning_trades', models.IntegerField(default=0)),
                ('losing_trades', models.IntegerField(default=0)),
                ('win_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Win rate as percentage', max_digits=10, null=True)),
                ('total_pnl', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('total_pnl_percentage', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('average_pnl', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('average_winner', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('average_loser', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('profit_factor', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('max_drawdown', models.DecimalField(blank=True, decimal_places=4, help_text='Maximum drawdown as percentage', max_digits=10, null=True)),
                ('max_drawdown_duration', models.IntegerField(blank=True, help_text='Duration of max drawdown in days', null=True)),
                ('sharpe_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('cagr', models.DecimalField(blank=True, decimal_places=4, help_text='Compound Annual Growth Rate as percentage', max_digits=10, null=True)),
                ('total_return', models.DecimalField(blank=True, decimal_places=4, help_text='Total return as percentage', max_digits=10, null=True)),
                ('equity_curve', models.JSONField(blank=True, default=list, help_text="Equity curve data points: [{'timestamp': '2024-01-01', 'equity': 10000}, ...]")),
                ('additional_stats', models.JSONField(blank=True, default=dict, help_text='Additional calculated statistics')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Backtest Statistics',
                'verbose_name_plural': 'Backtest Statistics',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('entry_timestamp', models.DateTimeField()),
                ('exit_timestamp', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=8, default=1.0, max_digits=20)),
                ('pnl', models.DecimalField(blank=True, decimal_places=8, help_text='Profit/Loss', max_digits=20, null=True)),
                ('pnl_percentage', models.DecimalField(blank=True, decimal_places=4, help_text='PnL as percentage', max_digits=10, null=True)),
                ('is_winner', models.BooleanField(blank=True, help_text='True if profitable trade', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional trade metadata (e.g., signal strength, indicator values)')),
            ],
            options={
                'verbose_name': 'Trade',
                'verbose_name_plural': 'Trades',
                'ordering': ['entry_timestamp'],
            },
        ),
    ]
