# Generated by Django 5.2.9 on 2025-12-06 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backtest_engine', '0001_initial'),
        ('market_data', '0004_add_validation_fields'),
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtest',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtests', to='strategies.strategydefinition'),
        ),
        migrations.AddField(
            model_name='backtest',
            name='strategy_assignment',
            field=models.ForeignKey(blank=True, help_text='Strategy assignment used (if available)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backtests', to='strategies.strategyassignment'),
        ),
        migrations.AddField(
            model_name='backtest',
            name='symbols',
            field=models.ManyToManyField(help_text='Symbols included in this backtest', related_name='backtests', to='market_data.symbol'),
        ),
        migrations.AddField(
            model_name='backteststatistics',
            name='backtest',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='backtest_engine.backtest'),
        ),
        migrations.AddField(
            model_name='backteststatistics',
            name='symbol',
            field=models.ForeignKey(blank=True, help_text='If None, these are portfolio-level statistics', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backtest_statistics', to='market_data.symbol'),
        ),
        migrations.AddField(
            model_name='trade',
            name='backtest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='backtest_engine.backtest'),
        ),
        migrations.AddField(
            model_name='trade',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='market_data.symbol'),
        ),
        migrations.AddIndex(
            model_name='backtest',
            index=models.Index(fields=['strategy', 'status'], name='backtest_en_strateg_50dac9_idx'),
        ),
        migrations.AddIndex(
            model_name='backtest',
            index=models.Index(fields=['status'], name='backtest_en_status_ced684_idx'),
        ),
        migrations.AddIndex(
            model_name='backtest',
            index=models.Index(fields=['-created_at'], name='backtest_en_created_cda53a_idx'),
        ),
        migrations.AddIndex(
            model_name='backteststatistics',
            index=models.Index(fields=['backtest', 'symbol'], name='backtest_en_backtes_f9da1c_idx'),
        ),
        migrations.AddIndex(
            model_name='backteststatistics',
            index=models.Index(fields=['backtest'], name='backtest_en_backtes_77f05d_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['backtest', 'symbol'], name='backtest_en_backtes_449e26_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['backtest', 'entry_timestamp'], name='backtest_en_backtes_c97d6d_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['symbol', 'entry_timestamp'], name='backtest_en_symbol__3454df_idx'),
        ),
    ]
