# Generated by Django 5.2.9 on 2025-12-06 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest_engine', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backteststatistics',
            name='backtest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='backtest_engine.backtest'),
        ),
    ]
