# Generated by Django 5.2.9 on 2025-12-06 13:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest_engine', '0003_alter_backteststatistics_backtest'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtest',
            name='bet_size_percentage',
            field=models.FloatField(default=100.0, help_text='Percentage of available capital to bet per trade (0.1-100.0)', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='backtest',
            name='initial_capital',
            field=models.DecimalField(decimal_places=2, default=10000.0, help_text='Initial capital for the backtest', max_digits=20, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
