# Generated by Django 5.2.9 on 2025-12-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest_engine', '0004_backtest_bet_size_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='max_drawdown',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Maximum drawdown percentage during the trade period', max_digits=10, null=True),
        ),
    ]
