# Generated by Django 5.2.9 on 2025-12-13 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest_engine', '0005_trade_max_drawdown'),
        ('live_trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtest',
            name='broker',
            field=models.ForeignKey(blank=True, help_text='Broker used for this backtest (optional - used for broker-aware symbol filtering)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backtests', to='live_trading.broker'),
        ),
    ]
