# Generated by Django 5.2.9 on 2026-04-11 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest_engine', '0009_hedge_lab_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtest',
            name='position_mode',
            field=models.CharField(choices=[('all', 'Long and short'), ('long', 'Long only'), ('short', 'Short only')], default='all', help_text='Which position directions to simulate: both modes, long only, or short only', max_length=10),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='hedge_enabled',
            field=models.BooleanField(default=False, help_text="If true, split each trade's bet between the strategy and hybrid VIX sleeve (VIXM/VIXY)"),
        ),
    ]
