# Generated by Django 5.2.9 on 2026-04-12 00:09

import backtest_engine.position_modes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest_engine', '0011_backtest_position_modes_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backtest',
            name='position_modes',
            field=models.JSONField(default=backtest_engine.position_modes.default_position_modes_list, help_text="Which directions to simulate: include 'long' and/or 'short' (at least one)"),
        ),
    ]
