# Generated by Django 5.2.9 on 2026-04-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest_engine', '0012_alter_backtest_position_modes'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtest',
            name='run_strategy_only_baseline',
            field=models.BooleanField(default=True, help_text='When hedge is enabled, also run a baseline (no-hedge) backtest to populate strategy_only comparison metrics'),
        ),
    ]
