# Generated by Django 5.2.9 on 2026-04-20 09:37

import backtest_engine.position_modes
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest_engine', '0015_strategy_symbol_snapshot_multi'),
        ('live_trading', '0003_add_separate_paper_real_money_credentials'),
        ('market_data', '0005_add_provider_s3_fields'),
        ('strategies', '0002_strategydefinition_required_tool_configs'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymbolBacktestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Optional name for this run', max_length=200)),
                ('start_date', models.DateTimeField(help_text='Run start date')),
                ('end_date', models.DateTimeField(help_text='Run end date')),
                ('split_ratio', models.FloatField(default=0.7, help_text='Training/test split ratio (e.g., 0.7 = 70% training, 30% testing)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('initial_capital', models.DecimalField(decimal_places=2, default=10000.0, help_text='Initial capital for the run', max_digits=20, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('bet_size_percentage', models.FloatField(default=100.0, help_text='Percentage of available capital to bet per trade (0.1-100.0)', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(100.0)])),
                ('strategy_parameters', models.JSONField(blank=True, default=dict, help_text='Strategy parameters used for this run')),
                ('hedge_enabled', models.BooleanField(default=False, help_text="If true, split each trade's bet between the strategy and hybrid VIX sleeve (VIXM/VIXY)")),
                ('run_strategy_only_baseline', models.BooleanField(default=True, help_text='When hedge is enabled, also run a baseline (no-hedge) run to populate comparison metrics')),
                ('hedge_config', models.JSONField(blank=True, default=dict, help_text='Hybrid VIX hedge parameters; defaults apply when empty')),
                ('position_modes', models.JSONField(default=backtest_engine.position_modes.default_position_modes_list, help_text="Which directions to simulate: include 'long' and/or 'short' (at least one)")),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if run failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Symbol backtest run',
                'verbose_name_plural': 'Symbol backtest runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SymbolBacktestStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_trades', models.IntegerField(default=0)),
                ('winning_trades', models.IntegerField(default=0)),
                ('losing_trades', models.IntegerField(default=0)),
                ('win_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Win rate as percentage', max_digits=10, null=True)),
                ('total_pnl', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('total_pnl_percentage', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('average_pnl', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('average_winner', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('average_loser', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('profit_factor', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('max_drawdown', models.DecimalField(blank=True, decimal_places=4, help_text='Peak-to-trough drawdown on the equity curve (percentage of capital)', max_digits=10, null=True)),
                ('max_drawdown_duration', models.IntegerField(blank=True, help_text='Duration of max drawdown in days', null=True)),
                ('avg_intra_trade_drawdown', models.DecimalField(blank=True, decimal_places=4, help_text='Average intra-trade adverse excursion (percentage), from OHLCV during each open position', max_digits=10, null=True)),
                ('worst_intra_trade_drawdown', models.DecimalField(blank=True, decimal_places=4, help_text='Largest intra-trade adverse excursion (percentage) among closed trades', max_digits=10, null=True)),
                ('sharpe_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('cagr', models.DecimalField(blank=True, decimal_places=4, help_text='Compound Annual Growth Rate as percentage', max_digits=10, null=True)),
                ('total_return', models.DecimalField(blank=True, decimal_places=4, help_text='Total return as percentage', max_digits=10, null=True)),
                ('equity_curve', models.JSONField(blank=True, default=list, help_text="Equity curve data points: [{'timestamp': '2024-01-01', 'equity': 10000}, ...]")),
                ('additional_stats', models.JSONField(blank=True, default=dict, help_text='Additional calculated statistics')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Symbol backtest statistics',
                'verbose_name_plural': 'Symbol backtest statistics',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SymbolBacktestTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('entry_timestamp', models.DateTimeField()),
                ('exit_timestamp', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=8, default=1.0, max_digits=20)),
                ('pnl', models.DecimalField(blank=True, decimal_places=8, help_text='Profit/Loss', max_digits=20, null=True)),
                ('pnl_percentage', models.DecimalField(blank=True, decimal_places=4, help_text='PnL as percentage', max_digits=10, null=True)),
                ('is_winner', models.BooleanField(blank=True, help_text='True if profitable trade', null=True)),
                ('max_drawdown', models.DecimalField(blank=True, decimal_places=4, help_text='Maximum drawdown percentage during the trade period', max_digits=10, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional trade metadata (e.g., signal strength, indicator values)')),
            ],
            options={
                'verbose_name': 'Symbol backtest trade',
                'verbose_name_plural': 'Symbol backtest trades',
                'ordering': ['entry_timestamp'],
            },
        ),
        migrations.RenameIndex(
            model_name='strategysymbolbacktestsnapshot',
            new_name='backtest_en_strateg_166b0e_idx',
            old_name='bt_ss_snap_str_sym_upd_idx',
        ),
        migrations.AddField(
            model_name='symbolbacktestrun',
            name='broker',
            field=models.ForeignKey(blank=True, help_text='Broker used for this run (optional - used for broker-aware filtering)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='symbol_backtest_runs', to='live_trading.broker'),
        ),
        migrations.AddField(
            model_name='symbolbacktestrun',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbol_backtest_runs', to='strategies.strategydefinition'),
        ),
        migrations.AddField(
            model_name='symbolbacktestrun',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbol_backtest_runs', to='market_data.symbol'),
        ),
        migrations.AddField(
            model_name='symbolbackteststatistics',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='backtest_engine.symbolbacktestrun'),
        ),
        migrations.AddField(
            model_name='symbolbackteststatistics',
            name='symbol',
            field=models.ForeignKey(blank=True, help_text='If None, these are run-level statistics', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='symbol_backtest_statistics', to='market_data.symbol'),
        ),
        migrations.AddField(
            model_name='symbolbacktesttrade',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='backtest_engine.symbolbacktestrun'),
        ),
        migrations.AddField(
            model_name='symbolbacktesttrade',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbol_backtest_trades', to='market_data.symbol'),
        ),
        migrations.AddIndex(
            model_name='symbolbacktestrun',
            index=models.Index(fields=['strategy', 'symbol', '-created_at'], name='backtest_en_strateg_981110_idx'),
        ),
        migrations.AddIndex(
            model_name='symbolbacktestrun',
            index=models.Index(fields=['strategy', 'status'], name='backtest_en_strateg_2be3c2_idx'),
        ),
        migrations.AddIndex(
            model_name='symbolbacktestrun',
            index=models.Index(fields=['status'], name='backtest_en_status_c33c38_idx'),
        ),
        migrations.AddIndex(
            model_name='symbolbacktestrun',
            index=models.Index(fields=['-created_at'], name='backtest_en_created_edaf39_idx'),
        ),
        migrations.AddIndex(
            model_name='symbolbackteststatistics',
            index=models.Index(fields=['run', 'symbol'], name='backtest_en_run_id_337eb0_idx'),
        ),
        migrations.AddIndex(
            model_name='symbolbackteststatistics',
            index=models.Index(fields=['run'], name='backtest_en_run_id_04debe_idx'),
        ),
        migrations.AddIndex(
            model_name='symbolbacktesttrade',
            index=models.Index(fields=['run', 'symbol'], name='backtest_en_run_id_485abb_idx'),
        ),
        migrations.AddIndex(
            model_name='symbolbacktesttrade',
            index=models.Index(fields=['run', 'entry_timestamp'], name='backtest_en_run_id_bf0201_idx'),
        ),
        migrations.AddIndex(
            model_name='symbolbacktesttrade',
            index=models.Index(fields=['symbol', 'entry_timestamp'], name='backtest_en_symbol__a8bec4_idx'),
        ),
    ]
