# Generated by Django 5.2.9 on 2026-04-20 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backtest_engine', '0016_symbolbacktestrun_symbolbackteststatistics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backtest',
            name='is_strategy_symbol_snapshot',
        ),
        migrations.DeleteModel(
            name='StrategySymbolBacktestSnapshot',
        ),
    ]
