# Generated by Django 5.2.9 on 2026-04-25 11:21

def backfill_symbol_run_parameter_sets(apps, schema_editor):
    """
    Populate SymbolBacktestRun.parameter_set for existing rows using deterministic signatures.
    """
    from decimal import Decimal
    import hashlib
    import json

    SymbolBacktestRun = apps.get_model('backtest_engine', 'SymbolBacktestRun')
    SymbolBacktestParameterSet = apps.get_model('backtest_engine', 'SymbolBacktestParameterSet')

    def _iso(dt):
        if dt is None:
            return None
        # migration-safe ISO with Z when possible
        s = dt.isoformat()
        return s.replace('+00:00', 'Z')

    def _normalize(obj):
        if obj is None:
            return None
        if isinstance(obj, Decimal):
            return str(obj)
        if isinstance(obj, float):
            return round(obj, 12)
        if isinstance(obj, (int, str, bool)):
            return obj
        if hasattr(obj, 'isoformat') and not isinstance(obj, (dict, list, tuple)):
            return _iso(obj)
        if isinstance(obj, dict):
            return {str(k): _normalize(v) for k, v in sorted(obj.items(), key=lambda kv: str(kv[0]))}
        if isinstance(obj, (list, tuple)):
            return [_normalize(v) for v in obj]
        return str(obj)

    def signature_for_payload(payload):
        canonical = json.dumps(payload, sort_keys=True, separators=(',', ':'), ensure_ascii=False)
        return hashlib.sha256(canonical.encode('utf-8')).hexdigest()

    for run in SymbolBacktestRun.objects.all().iterator():
        if getattr(run, 'parameter_set_id', None):
            continue
        modes = run.position_modes or []
        modes = [m for m in modes if m in ('long', 'short')]
        modes = sorted(set(modes))
        payload = _normalize(
            {
                'strategy_id': int(run.strategy_id),
                'broker_id': int(run.broker_id) if run.broker_id is not None else None,
                'start_date': _iso(run.start_date),
                'end_date': _iso(run.end_date),
                'split_ratio': float(run.split_ratio),
                'initial_capital': str(run.initial_capital),
                'bet_size_percentage': float(run.bet_size_percentage),
                'strategy_parameters': run.strategy_parameters or {},
                'position_modes': modes,
                'hedge_enabled': bool(run.hedge_enabled),
                'run_strategy_only_baseline': bool(run.run_strategy_only_baseline),
                'hedge_config': run.hedge_config or {},
            }
        )
        sig = signature_for_payload(payload)
        ps, _created = SymbolBacktestParameterSet.objects.get_or_create(
            signature=sig,
            defaults={
                'strategy_id': run.strategy_id,
                'broker_id': run.broker_id,
                'parameters': payload,
            },
        )
        run.parameter_set_id = ps.signature
        run.save(update_fields=['parameter_set'])


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest_engine', '0017_remove_backtest_is_strategy_symbol_snapshot_and_more'),
        ('live_trading', '0003_add_separate_paper_real_money_credentials'),
        ('strategies', '0002_strategydefinition_required_tool_configs'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymbolBacktestParameterSet',
            fields=[
                ('signature', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='symbol_backtest_parameter_sets', to='live_trading.broker')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbol_backtest_parameter_sets', to='strategies.strategydefinition')),
            ],
            options={
                'verbose_name': 'Symbol backtest parameter set',
                'verbose_name_plural': 'Symbol backtest parameter sets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='symbolbacktestrun',
            name='parameter_set',
            field=models.ForeignKey(blank=True, help_text='Deterministic global identifier derived from chosen parameters (used to group runs across symbols)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='backtest_engine.symbolbacktestparameterset'),
        ),
        migrations.AddIndex(
            model_name='symbolbacktestparameterset',
            index=models.Index(fields=['strategy', '-created_at'], name='backtest_en_strateg_d0abb6_idx'),
        ),
        migrations.AddIndex(
            model_name='symbolbacktestparameterset',
            index=models.Index(fields=['broker'], name='backtest_en_broker__db32a4_idx'),
        ),
        migrations.RunPython(code=backfill_symbol_run_parameter_sets, reverse_code=migrations.RunPython.noop),
    ]
