# Generated by Django 5.2.9 on 2026-04-25 11:40

def backfill_parameter_set_labels(apps, schema_editor):
    """
    Best-effort: if a parameter set has empty label, set it from the oldest run name that uses it.
    """
    SymbolBacktestRun = apps.get_model('backtest_engine', 'SymbolBacktestRun')
    SymbolBacktestParameterSet = apps.get_model('backtest_engine', 'SymbolBacktestParameterSet')

    for ps in SymbolBacktestParameterSet.objects.filter(label='').iterator():
        run = (
            SymbolBacktestRun.objects.filter(parameter_set_id=ps.signature)
            .exclude(name='')
            .order_by('created_at')
            .first()
        )
        if run and run.name:
            ps.label = run.name[:200]
            ps.save(update_fields=['label'])


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest_engine', '0018_symbol_run_parameter_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbolbacktestparameterset',
            name='label',
            field=models.CharField(blank=True, help_text='Human-friendly name for this parameter set (used in UI selectors)', max_length=200),
        ),
        migrations.RunPython(code=backfill_parameter_set_labels, reverse_code=migrations.RunPython.noop),
    ]
