# Generated by Django 5.2.9 on 2025-12-13 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backtest_engine', '0005_trade_max_drawdown'),
        ('market_data', '0004_add_validation_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Broker name (e.g., Alpaca, Interactive Brokers)', max_length=100, unique=True)),
                ('code', models.CharField(help_text="Unique broker code identifier (e.g., 'ALPACA', 'IB')", max_length=50, unique=True)),
                ('paper_trading_api_key', models.CharField(blank=True, help_text='Paper trading API key (should be encrypted in production)', max_length=500, null=True)),
                ('paper_trading_api_secret', models.CharField(blank=True, help_text='Paper trading API secret (should be encrypted in production)', max_length=500, null=True)),
                ('real_money_api_key', models.CharField(blank=True, help_text='Real money trading API key (should be encrypted in production)', max_length=500, null=True)),
                ('real_money_api_secret', models.CharField(blank=True, help_text='Real money trading API secret (should be encrypted in production)', max_length=500, null=True)),
                ('api_config', models.JSONField(blank=True, default=dict, help_text='Broker-specific configuration (e.g., base_url, timeout, rate_limits)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this broker is active and available for use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Broker',
                'verbose_name_plural': 'Brokers',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='live_tradin_code_fb6e31_idx'), models.Index(fields=['is_active'], name='live_tradin_is_acti_6f6a07_idx')],
            },
        ),
        migrations.CreateModel(
            name='LiveTradingDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Optional name for this deployment', max_length=200)),
                ('position_mode', models.CharField(choices=[('all', 'All'), ('long', 'Long Only'), ('short', 'Short Only')], help_text='Position mode from the selected backtest', max_length=10)),
                ('deployment_type', models.CharField(choices=[('paper', 'Paper Trading'), ('real_money', 'Real Money Trading')], default='paper', help_text='Type of deployment (paper or real money)', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('evaluating', 'Evaluating (Paper Trading)'), ('passed', 'Evaluation Passed'), ('failed', 'Evaluation Failed'), ('active', 'Active'), ('paused', 'Paused'), ('stopped', 'Stopped')], default='pending', help_text='Current deployment status', max_length=20)),
                ('evaluation_criteria', models.JSONField(default=dict, help_text='Evaluation criteria: {min_trades: int, min_sharpe_ratio: float, min_pnl: float}')),
                ('evaluation_results', models.JSONField(blank=True, default=dict, help_text='Evaluation results: {trades_count: int, sharpe_ratio: float, total_pnl: float, passed: bool, evaluated_at: datetime}')),
                ('initial_capital', models.DecimalField(decimal_places=2, help_text='Initial capital for the deployment (from backtest)', max_digits=20)),
                ('bet_size_percentage', models.FloatField(help_text='Bet size percentage per trade (from backtest)')),
                ('strategy_parameters', models.JSONField(blank=True, default=dict, help_text='Strategy parameters (from backtest)')),
                ('started_at', models.DateTimeField(blank=True, help_text='When the deployment was started', null=True)),
                ('evaluated_at', models.DateTimeField(blank=True, help_text='When the evaluation was completed', null=True)),
                ('activated_at', models.DateTimeField(blank=True, help_text='When the deployment was activated (for real money)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('backtest', models.ForeignKey(help_text='Backtest used as the basis for this deployment', on_delete=django.db.models.deletion.CASCADE, related_name='live_deployments', to='backtest_engine.backtest')),
                ('broker', models.ForeignKey(help_text='Broker used for this deployment', on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='live_trading.broker')),
                ('symbols', models.ManyToManyField(help_text='Symbols included in this deployment', related_name='live_deployments', to='market_data.symbol')),
            ],
            options={
                'verbose_name': 'Live Trading Deployment',
                'verbose_name_plural': 'Live Trading Deployments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_mode', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], help_text='Position mode for this trade', max_length=10)),
                ('trade_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], help_text='Trade type (buy or sell)', max_length=10)),
                ('entry_price', models.DecimalField(decimal_places=8, help_text='Entry price', max_digits=20)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=8, help_text='Exit price (null if trade is still open)', max_digits=20, null=True)),
                ('quantity', models.DecimalField(decimal_places=8, help_text='Quantity traded', max_digits=20)),
                ('entry_timestamp', models.DateTimeField(help_text='When the trade was entered')),
                ('exit_timestamp', models.DateTimeField(blank=True, help_text='When the trade was exited (null if trade is still open)', null=True)),
                ('pnl', models.DecimalField(blank=True, decimal_places=8, help_text='Profit/Loss (null if trade is still open)', max_digits=20, null=True)),
                ('pnl_percentage', models.DecimalField(blank=True, decimal_places=4, help_text='PnL as percentage', max_digits=10, null=True)),
                ('is_winner', models.BooleanField(blank=True, help_text='True if profitable trade (null if trade is still open)', null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', help_text='Trade status', max_length=20)),
                ('broker_order_id', models.CharField(blank=True, help_text="Broker's order ID for reference", max_length=200, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional trade metadata (e.g., signal strength, fees, slippage)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.ForeignKey(help_text='Symbol traded', on_delete=django.db.models.deletion.CASCADE, related_name='live_trades', to='market_data.symbol')),
                ('deployment', models.ForeignKey(help_text='Deployment that executed this trade', on_delete=django.db.models.deletion.CASCADE, related_name='live_trades', to='live_trading.livetradingdeployment')),
            ],
            options={
                'verbose_name': 'Live Trade',
                'verbose_name_plural': 'Live Trades',
                'ordering': ['-entry_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SymbolBrokerAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_active', models.BooleanField(default=False, help_text='Whether the symbol can be traded long on this broker')),
                ('short_active', models.BooleanField(default=False, help_text='Whether the symbol can be traded short on this broker')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When broker capabilities were last verified via API', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broker', models.ForeignKey(help_text='Broker where this symbol can be traded', on_delete=django.db.models.deletion.CASCADE, related_name='symbol_associations', to='live_trading.broker')),
                ('symbol', models.ForeignKey(help_text='Symbol that can be traded on this broker', on_delete=django.db.models.deletion.CASCADE, related_name='broker_associations', to='market_data.symbol')),
            ],
            options={
                'verbose_name': 'Symbol-Broker Association',
                'verbose_name_plural': 'Symbol-Broker Associations',
                'ordering': ['symbol__ticker', 'broker__name'],
            },
        ),
        migrations.AddIndex(
            model_name='livetradingdeployment',
            index=models.Index(fields=['broker', 'status'], name='live_tradin_broker__38f917_idx'),
        ),
        migrations.AddIndex(
            model_name='livetradingdeployment',
            index=models.Index(fields=['status'], name='live_tradin_status_074f93_idx'),
        ),
        migrations.AddIndex(
            model_name='livetradingdeployment',
            index=models.Index(fields=['deployment_type', 'status'], name='live_tradin_deploym_3aa6d6_idx'),
        ),
        migrations.AddIndex(
            model_name='livetradingdeployment',
            index=models.Index(fields=['-created_at'], name='live_tradin_created_12c47a_idx'),
        ),
        migrations.AddIndex(
            model_name='livetrade',
            index=models.Index(fields=['deployment', 'symbol'], name='live_tradin_deploym_2e822d_idx'),
        ),
        migrations.AddIndex(
            model_name='livetrade',
            index=models.Index(fields=['deployment', 'status'], name='live_tradin_deploym_a2855c_idx'),
        ),
        migrations.AddIndex(
            model_name='livetrade',
            index=models.Index(fields=['deployment', 'entry_timestamp'], name='live_tradin_deploym_81e201_idx'),
        ),
        migrations.AddIndex(
            model_name='livetrade',
            index=models.Index(fields=['symbol', 'entry_timestamp'], name='live_tradin_symbol__f1e1f0_idx'),
        ),
        migrations.AddIndex(
            model_name='livetrade',
            index=models.Index(fields=['status'], name='live_tradin_status_7e8afc_idx'),
        ),
        migrations.AddIndex(
            model_name='symbolbrokerassociation',
            index=models.Index(fields=['symbol', 'broker'], name='live_tradin_symbol__fad8c7_idx'),
        ),
        migrations.AddIndex(
            model_name='symbolbrokerassociation',
            index=models.Index(fields=['broker', 'long_active'], name='live_tradin_broker__e8f8e6_idx'),
        ),
        migrations.AddIndex(
            model_name='symbolbrokerassociation',
            index=models.Index(fields=['broker', 'short_active'], name='live_tradin_broker__fafa48_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='symbolbrokerassociation',
            unique_together={('symbol', 'broker')},
        ),
    ]
