# Generated by Django 5.2.9 on 2025-12-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_trading', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broker',
            name='paper_trading_api_key',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='paper_trading_api_secret',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='real_money_api_key',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='real_money_api_secret',
        ),
        migrations.AddField(
            model_name='broker',
            name='api_key',
            field=models.CharField(blank=True, help_text='API key (should be encrypted in production)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='endpoint_url',
            field=models.URLField(blank=True, help_text='Broker API endpoint URL (e.g., https://paper-api.alpaca.markets)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='secret_key',
            field=models.CharField(blank=True, help_text='API secret key (should be encrypted in production)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='api_config',
            field=models.JSONField(blank=True, default=dict, help_text='Broker-specific configuration (e.g., timeout, rate_limits)'),
        ),
        migrations.AlterField(
            model_name='broker',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Whether this broker is active and connection tested successfully'),
        ),
    ]
