# Generated by Django 5.2.9 on 2025-12-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_trading', '0002_update_broker_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='broker',
            name='live_tradin_is_acti_6f6a07_idx',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='endpoint_url',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='secret_key',
        ),
        migrations.AddField(
            model_name='broker',
            name='paper_trading_active',
            field=models.BooleanField(default=False, help_text='Whether paper trading credentials are tested and active'),
        ),
        migrations.AddField(
            model_name='broker',
            name='paper_trading_api_key',
            field=models.CharField(blank=True, help_text='Paper trading API key (should be encrypted in production)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='paper_trading_endpoint_url',
            field=models.URLField(blank=True, help_text='Paper trading API endpoint URL (e.g., https://paper-api.alpaca.markets)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='paper_trading_secret_key',
            field=models.CharField(blank=True, help_text='Paper trading API secret key (should be encrypted in production)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='real_money_active',
            field=models.BooleanField(default=False, help_text='Whether real money trading credentials are tested and active'),
        ),
        migrations.AddField(
            model_name='broker',
            name='real_money_api_key',
            field=models.CharField(blank=True, help_text='Real money trading API key (should be encrypted in production)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='real_money_endpoint_url',
            field=models.URLField(blank=True, help_text='Real money trading API endpoint URL (e.g., https://api.alpaca.markets)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='real_money_secret_key',
            field=models.CharField(blank=True, help_text='Real money trading API secret key (should be encrypted in production)', max_length=500, null=True),
        ),
        migrations.AddIndex(
            model_name='broker',
            index=models.Index(fields=['paper_trading_active'], name='live_tradin_paper_t_32c9c1_idx'),
        ),
        migrations.AddIndex(
            model_name='broker',
            index=models.Index(fields=['real_money_active'], name='live_tradin_real_mo_280553_idx'),
        ),
    ]
