# Generated by Django 5.2.9 on 2026-04-25 22:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest_engine', '0019_parameter_set_label'),
        ('live_trading', '0003_add_separate_paper_real_money_credentials'),
        ('market_data', '0006_strategy_deployment_v2'),
        ('strategies', '0002_strategydefinition_required_tool_configs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livetradingdeployment',
            name='backtest',
        ),
        migrations.RemoveField(
            model_name='livetradingdeployment',
            name='broker',
        ),
        migrations.RemoveField(
            model_name='livetradingdeployment',
            name='symbols',
        ),
        migrations.AlterField(
            model_name='livetrade',
            name='broker_order_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='livetrade',
            name='entry_price',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='livetrade',
            name='entry_timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='livetrade',
            name='exit_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='livetrade',
            name='exit_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livetrade',
            name='is_winner',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livetrade',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='livetrade',
            name='pnl',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='livetrade',
            name='pnl_percentage',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='livetrade',
            name='position_mode',
            field=models.CharField(choices=[('long', 'Long'), ('short', 'Short')], max_length=10),
        ),
        migrations.AlterField(
            model_name='livetrade',
            name='quantity',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='livetrade',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='livetrade',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_trades', to='market_data.symbol'),
        ),
        migrations.AlterField(
            model_name='livetrade',
            name='trade_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10),
        ),
        migrations.AlterField(
            model_name='symbolbrokerassociation',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbol_associations', to='live_trading.broker'),
        ),
        migrations.AlterField(
            model_name='symbolbrokerassociation',
            name='long_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='symbolbrokerassociation',
            name='short_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='symbolbrokerassociation',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_associations', to='market_data.symbol'),
        ),
        migrations.AlterField(
            model_name='symbolbrokerassociation',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DeploymentSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_mode', models.CharField(choices=[('all', 'All'), ('long', 'Long Only'), ('short', 'Short Only')], default='long', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('flagged_for_disable', 'Flagged for Disable'), ('disabled', 'Disabled'), ('pending_enable', 'Pending Enable')], default='active', max_length=24)),
                ('sharpe_long', models.FloatField(blank=True, null=True)),
                ('sharpe_short', models.FloatField(blank=True, null=True)),
                ('max_dd_long', models.FloatField(blank=True, null=True)),
                ('max_dd_short', models.FloatField(blank=True, null=True)),
                ('total_trades_long', models.IntegerField(blank=True, null=True)),
                ('total_trades_short', models.IntegerField(blank=True, null=True)),
                ('color_long', models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('red', 'Red'), ('black', 'Black'), ('gray', 'Unknown')], default='gray', max_length=10)),
                ('color_short', models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('red', 'Red'), ('black', 'Black'), ('gray', 'Unknown')], default='gray', max_length=10)),
                ('color_overall', models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('red', 'Red'), ('black', 'Black'), ('gray', 'Unknown')], default='gray', max_length=10)),
                ('tier', models.CharField(choices=[('gt50', 'Trades > 50'), ('gt20', 'Trades > 20'), ('gt10', 'Trades > 10'), ('gt0', 'Trades > 0'), ('none', 'No trades')], default='none', max_length=8)),
                ('priority', models.IntegerField(default=0, help_text='Order within the deployment (lower runs first); seeded by selection helper')),
                ('last_signal_at', models.DateTimeField(blank=True, null=True)),
                ('last_evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployment_symbols', to='market_data.symbol')),
            ],
            options={
                'verbose_name': 'Deployment Symbol',
                'verbose_name_plural': 'Deployment Symbols',
                'ordering': ['priority', 'symbol__ticker'],
            },
        ),
        migrations.AddField(
            model_name='livetrade',
            name='deployment_symbol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_trades', to='live_trading.deploymentsymbol'),
        ),
        migrations.CreateModel(
            name='StrategyDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Optional name for this deployment', max_length=200)),
                ('position_mode', models.CharField(choices=[('all', 'All'), ('long', 'Long Only'), ('short', 'Short Only')], default='long', max_length=10)),
                ('deployment_type', models.CharField(choices=[('paper', 'Paper Trading'), ('real_money', 'Real Money Trading')], default='paper', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('evaluating', 'Evaluating (Paper Trading)'), ('passed', 'Evaluation Passed'), ('failed', 'Evaluation Failed'), ('paused', 'Paused'), ('stopped', 'Stopped')], default='pending', max_length=20)),
                ('initial_capital', models.DecimalField(decimal_places=2, default=10000.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('bet_size_percentage', models.FloatField(default=100.0)),
                ('strategy_parameters', models.JSONField(blank=True, default=dict)),
                ('evaluation_criteria', models.JSONField(blank=True, default=dict)),
                ('evaluation_results', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('last_signal_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strategy_deployments', to='live_trading.broker')),
                ('parameter_set', models.ForeignKey(help_text='Global single-symbol backtest parent that defines configuration', on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='backtest_engine.symbolbacktestparameterset')),
                ('parent_deployment', models.ForeignKey(blank=True, help_text='Set when this real-money deployment was promoted from a paper deployment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_deployments', to='live_trading.strategydeployment')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='strategies.strategydefinition')),
            ],
            options={
                'verbose_name': 'Strategy Deployment',
                'verbose_name_plural': 'Strategy Deployments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='deploymentsymbol',
            name='deployment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployment_symbols', to='live_trading.strategydeployment'),
        ),
        migrations.CreateModel(
            name='DeploymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('deploy_created', 'Deployment Created'), ('deploy_activated', 'Deployment Activated'), ('deploy_paused', 'Deployment Paused'), ('deploy_stopped', 'Deployment Stopped'), ('deploy_failed', 'Deployment Failed'), ('promote_to_real', 'Promoted to Real Money'), ('symbol_added', 'Symbol Added'), ('symbol_disabled', 'Symbol Disabled'), ('symbol_flagged', 'Symbol Flagged for Disable'), ('symbol_enabled', 'Symbol Enabled'), ('symbol_pending_enable', 'Symbol Pending Enable'), ('color_changed', 'Snapshot Color Changed'), ('task_tick', 'Scheduled Task Tick'), ('signal_evaluated', 'Signal Evaluated'), ('order_placed', 'Order Placed'), ('order_filled', 'Order Filled'), ('order_failed', 'Order Failed'), ('trade_opened', 'Trade Opened'), ('trade_closed', 'Trade Closed'), ('positions_synced', 'Positions Synced'), ('recalc_started', 'Snapshot Recalc Started'), ('recalc_finished', 'Snapshot Recalc Finished'), ('evaluation_passed', 'Evaluation Passed'), ('evaluation_failed', 'Evaluation Failed'), ('error', 'Error'), ('info', 'Info')], max_length=40)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10)),
                ('actor_type', models.CharField(choices=[('user', 'User'), ('task', 'Celery Task'), ('system', 'System'), ('broker', 'Broker')], default='system', max_length=10)),
                ('actor_id', models.CharField(blank=True, help_text='Identifier for who/what performed the action (user id, celery task id, etc.)', max_length=200)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deployment_symbol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='live_trading.deploymentsymbol')),
                ('deployment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='live_trading.strategydeployment')),
            ],
            options={
                'verbose_name': 'Deployment Event',
                'verbose_name_plural': 'Deployment Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='livetrade',
            name='deployment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_trades', to='live_trading.strategydeployment'),
        ),
        migrations.AddIndex(
            model_name='strategydeployment',
            index=models.Index(fields=['strategy', 'status'], name='live_tradin_strateg_3ca6e4_idx'),
        ),
        migrations.AddIndex(
            model_name='strategydeployment',
            index=models.Index(fields=['broker', 'status'], name='live_tradin_broker__b1b839_idx'),
        ),
        migrations.AddIndex(
            model_name='strategydeployment',
            index=models.Index(fields=['parameter_set'], name='live_tradin_paramet_d1b24d_idx'),
        ),
        migrations.AddIndex(
            model_name='strategydeployment',
            index=models.Index(fields=['deployment_type', 'status'], name='live_tradin_deploym_2d7075_idx'),
        ),
        migrations.AddIndex(
            model_name='strategydeployment',
            index=models.Index(fields=['-created_at'], name='live_tradin_created_2176ea_idx'),
        ),
        migrations.AddIndex(
            model_name='deploymentsymbol',
            index=models.Index(fields=['deployment', 'status'], name='live_tradin_deploym_46e938_idx'),
        ),
        migrations.AddIndex(
            model_name='deploymentsymbol',
            index=models.Index(fields=['deployment', 'priority'], name='live_tradin_deploym_dfe551_idx'),
        ),
        migrations.AddIndex(
            model_name='deploymentsymbol',
            index=models.Index(fields=['status'], name='live_tradin_status_0420f7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='deploymentsymbol',
            unique_together={('deployment', 'symbol')},
        ),
        migrations.AddIndex(
            model_name='deploymentevent',
            index=models.Index(fields=['deployment', '-created_at'], name='live_tradin_deploym_ec2ccf_idx'),
        ),
        migrations.AddIndex(
            model_name='deploymentevent',
            index=models.Index(fields=['event_type', '-created_at'], name='live_tradin_event_t_df9c13_idx'),
        ),
        migrations.AddIndex(
            model_name='deploymentevent',
            index=models.Index(fields=['deployment', 'event_type', '-created_at'], name='live_tradin_deploym_f0ed44_idx'),
        ),
        migrations.AddIndex(
            model_name='deploymentevent',
            index=models.Index(fields=['level', '-created_at'], name='live_tradin_level_d8b60d_idx'),
        ),
        migrations.DeleteModel(
            name='LiveTradingDeployment',
        ),
    ]
