# Generated by Django 5.2.9 on 2026-04-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_trading', '0004_strategy_deployment_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategydeployment',
            name='hedge_config',
            field=models.JSONField(blank=True, default=dict, help_text='Hybrid VIX hedge parameters (merged with defaults at order time).'),
        ),
        migrations.AddField(
            model_name='strategydeployment',
            name='hedge_enabled',
            field=models.BooleanField(default=False, help_text='If true, split each entry bet between the strategy symbol and a VIX sleeve (same hybrid logic as backtests; inherited from symbol runs on deploy).'),
        ),
    ]
